<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Element119\ResetBookmarkUi\Controller\Adminhtml\Bookmarks\Reset as BookmarkUiResetter;
use Magento\Backend\Block\Page\Header;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Header $block */
$part = $block->getShowPart();
?>
<?php if ($part === 'logo'): ?>
    <?php $edition = $block->hasEdition()
        ? $escaper->escapeHtml("data-edition=\"{$block->getEdition()}\"")
        : ''; ?>
    <?php $logoSrc = $escaper->escapeHtml(
        $block->hasLogoImageSrc() ? $block->getLogoImageSrc() : 'images/magento-logo.svg'
    ); ?>

    <a href="<?= $escaper->escapeUrl($block->getHomeLink()); ?>"
       <?= $escaper->escapeHtml($edition); ?>
       class="logo">
        <img class="logo-img"
             src="<?= $escaper->escapeUrl($block->getViewFileUrl($logoSrc)); ?>"
             alt="<?= $escaper->escapeHtml(__('Magento Admin Panel')); ?>"
             title="<?= $escaper->escapeHtml(__('Magento Admin Panel')); ?>"/>
    </a>
<?php elseif ($part === 'user'): ?>
    <div class="admin-user admin__action-dropdown-wrap">
        <a href="<?= $escaper->escapeUrl($block->getUrl('adminhtml/system_account/index')); ?>"
           class="admin__action-dropdown"
           title="<?= $escaper->escapeHtml(__('My Account')); ?>"
           data-mage-init='{"dropdown":{}}'
           data-toggle="dropdown">
            <span class="admin__action-dropdown-text">
                <span class="admin-user-account-text">
                    <?= $escaper->escapeHtml($block->getUser()->getUserName()); ?>
                </span>
            </span>
        </a>
        <ul class="admin__action-dropdown-menu">
            <?php if ($block->getAuthorization()->isAllowed('Magento_Backend::myaccount')): ?>
                <li>
                    <a href="<?= $escaper->escapeUrl($block->getUrl('adminhtml/system_account/index')); ?>"
                       <?= /** @noEscape */ $block->getUiId('user', 'account', 'settings'); ?>
                       title="<?= $escaper->escapeHtml(__('Account Setting')); ?>">
                        <?= $escaper->escapeHtml(__('Account Setting')); ?>
                        <span class="admin-user-name">
                            <?= $escaper->escapeHtml("({$block->getUser()->getUserName()})"); ?>
                        </span>
                    </a>
                </li>
            <?php endif; ?>

            <li>
                <a href="<?= $escaper->escapeUrl($block->getBaseUrl()); ?>"
                   title="<?= $escaper->escapeHtml(__('Customer View')); ?>"
                   target="_blank"
                   class="store-front">
                    <?= $escaper->escapeHtml(__('Customer View')); ?>
                </a>
            </li>

            <?php if ($block->getAuthorization()->isAllowed(BookmarkUiResetter::ADMIN_RESOURCE)): ?>
                <li>
                    <a href="<?= $escaper->escapeUrl($block->getUrl(BookmarkUiResetter::ADMIN_ROUTE)); ?>"
                       title="<?= $escaper->escapeHtml(__('Reset Bookmark UI')); ?>">
                        <?= $escaper->escapeHtml(__('Reset Bookmark UI')); ?>
                    </a>
                </li>
            <?php endif; ?>

            <li>
                <a href="<?= $escaper->escapeUrl($block->getLogoutLink()); ?>"
                   class="account-signout"
                   title="<?= $escaper->escapeHtml(__('Sign Out')); ?>">
                    <?= $escaper->escapeHtml(__('Sign Out')); ?>
                </a>
            </li>
        </ul>
    </div>
<?php elseif ($part === 'other'): ?>
    <?= $block->getChildHtml(); ?>
<?php endif; ?>
